{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.names.fullname" . }}-pvc
  namespace: {{ .Release.namespace }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
  - {{ . | quote }}
  {{- end }}
  {{- else }}
  - {{ .Values.persistence.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeMode: Filesystem
{{- end }}
